export interface ZimCity {
  id: string;
  name: string;
  province: string;
  lat: number;
  lng: number;
  popularSuburbs?: string[];
  isMajorCity?: boolean;
}

export const ZIM_MAJOR_CITIES: ZimCity[] = [
  {
    id: 'harare',
    name: 'Harare',
    province: 'Harare Metropolitan',
    lat: -17.8292,
    lng: 31.0522,
    isMajorCity: true,
    popularSuburbs: [
      'Harare CBD',
      'Avondale',
      'Borrowdale',
      'Eastlea',
      'Mount Pleasant',
      'Mbare Musika',
      'Southerton',
      'Highfield',
      'Westgate',
      'Greendale',
      'Belvedere',
      'Hatfield',
      'Waterfalls',
      'Mabvuku',
      'Glen View',
    ],
  },
  {
    id: 'bulawayo',
    name: 'Bulawayo',
    province: 'Bulawayo Metropolitan',
    lat: -20.1553,
    lng: 28.5843,
    isMajorCity: true,
    popularSuburbs: [
      'Bulawayo CBD',
      'Hillside',
      'Kumalo',
      'Suburbs',
      'Nkulumane',
      'Luveve',
      'Cowdray Park',
      'Ascot',
      'Famona',
      'Belmont',
    ],
  },
  {
    id: 'chitungwiza',
    name: 'Chitungwiza',
    province: 'Harare Metropolitan',
    lat: -18.0125,
    lng: 31.0667,
    isMajorCity: true,
    popularSuburbs: [
      'Town Centre',
      'Makoni',
      'Unit L',
      'Unit C',
      'Unit J',
      "St Mary's",
      'Zengeza 1-5',
      'Seke',
    ],
  },
  {
    id: 'mutare',
    name: 'Mutare',
    province: 'Manicaland',
    lat: -18.9728,
    lng: 32.6694,
    isMajorCity: true,
    popularSuburbs: ['Mutare CBD', 'Chikanga', 'Dangamvura', 'Murambi', 'Palmerstone', 'Sakubva'],
  },
  {
    id: 'gweru',
    name: 'Gweru',
    province: 'Midlands',
    lat: -19.4608,
    lng: 29.8144,
    isMajorCity: true,
    popularSuburbs: ['Gweru CBD', 'Mkoba', 'Southdowns', 'Lundi Park', 'Kopje'],
  },
  {
    id: 'kwekwe',
    name: 'Kwekwe',
    province: 'Midlands',
    lat: -18.9281,
    lng: 29.8148,
    isMajorCity: true,
    popularSuburbs: ['Kwekwe CBD', 'Mbizo', 'Redcliff', 'Amaveni'],
  },
  {
    id: 'masvingo',
    name: 'Masvingo',
    province: 'Masvingo',
    lat: -20.0744,
    lng: 30.8328,
    isMajorCity: true,
    popularSuburbs: ['Masvingo CBD', 'Mucheke', 'Rujeko', 'Target Kopje', 'Rhodene'],
  },
  {
    id: 'victoria_falls',
    name: 'Victoria Falls',
    province: 'Matabeleland North',
    lat: -17.9317,
    lng: 25.8307,
    isMajorCity: true,
    popularSuburbs: ['Town Centre', 'Chinotimba', 'Mkhosana', 'Cresta Sprayview area'],
  },
  {
    id: 'kadoma',
    name: 'Kadoma',
    province: 'Mashonaland West',
    lat: -18.3333,
    lng: 29.9167,
    popularSuburbs: ['Kadoma CBD', 'Rimuka', 'Ingezi', 'Cam & Motor'],
  },
  {
    id: 'chinhoyi',
    name: 'Chinhoyi',
    province: 'Mashonaland West',
    lat: -17.3667,
    lng: 30.2,
    popularSuburbs: ['Chinhoyi CBD', 'Orange Grove', 'Shackleton', 'Chikonohono'],
  },
  {
    id: 'marondera',
    name: 'Marondera',
    province: 'Mashonaland East',
    lat: -18.1856,
    lng: 31.5519,
    popularSuburbs: ['Marondera CBD', 'Dombotombo', 'Nyameni', 'Cherutombo'],
  },
  {
    id: 'norton',
    name: 'Norton',
    province: 'Mashonaland West',
    lat: -17.8833,
    lng: 30.7,
    popularSuburbs: ['Katanga', 'Knowe', 'Twinlakes', 'Govans'],
  },
  {
    id: 'zvishavane',
    name: 'Zvishavane',
    province: 'Midlands',
    lat: -20.3333,
    lng: 30.0667,
    popularSuburbs: ['Zvishavane CBD', 'Mandava', 'Maglas', 'Kandodo'],
  },
  {
    id: 'bindura',
    name: 'Bindura',
    province: 'Mashonaland Central',
    lat: -17.3,
    lng: 31.3333,
    popularSuburbs: ['Bindura CBD', 'Chipadze', 'Aerodrome', 'Brockley'],
  },
  {
    id: 'hwange',
    name: 'Hwange',
    province: 'Matabeleland North',
    lat: -18.3647,
    lng: 23.5983,
    popularSuburbs: ['Colliery', 'Baobab', 'Number 1', 'Empumalanga'],
  },
  {
    id: 'beitbridge',
    name: 'Beitbridge',
    province: 'Matabeleland South',
    lat: -22.2167,
    lng: 30.0,
    popularSuburbs: ['Border Post Area', 'Dulivhadzimu', 'Medium Density'],
  },
  {
    id: 'rusape',
    name: 'Rusape',
    province: 'Manicaland',
    lat: -18.5333,
    lng: 32.1167,
    popularSuburbs: ['Rusape CBD', 'Vengere', 'Castle Koppie'],
  },
  {
    id: 'kariba',
    name: 'Kariba',
    province: 'Mashonaland West',
    lat: -16.5167,
    lng: 28.8,
    popularSuburbs: ['Kariba Heights', 'Nyamhunga', 'Mahombekombe'],
  },
  {
    id: 'gwanda',
    name: 'Gwanda',
    province: 'Matabeleland South',
    lat: -20.9333,
    lng: 29.0,
    popularSuburbs: ['Gwanda CBD', 'Phakama', 'Jahunda'],
  },
  {
    id: 'chegutu',
    name: 'Chegutu',
    province: 'Mashonaland West',
    lat: -18.1303,
    lng: 30.1408,
    popularSuburbs: ['Chegutu CBD', 'Pfupajena', 'Hintonville'],
  },
  {
    id: 'shurugwi',
    name: 'Shurugwi',
    province: 'Midlands',
    lat: -19.6667,
    lng: 30.0,
    popularSuburbs: ['Shurugwi Town', 'Railway Block', 'Peak Mine'],
  },
  {
    id: 'chipinge',
    name: 'Chipinge',
    province: 'Manicaland',
    lat: -20.2,
    lng: 32.6167,
    popularSuburbs: ['Chipinge Town', 'Gaza', 'Medu'],
  },
  {
    id: 'ruwa',
    name: 'Ruwa',
    province: 'Harare Metropolitan',
    lat: -17.8897,
    lng: 31.2447,
    popularSuburbs: ['Ruwa Centre', 'Damofalls', 'Zimre Park', 'Springvale'],
  },
  {
    id: 'epworth',
    name: 'Epworth',
    province: 'Harare Metropolitan',
    lat: -17.8833,
    lng: 31.15,
    popularSuburbs: ['Overspill', 'Domboramwari', 'Chinamano'],
  },
  {
    id: 'chiredzi',
    name: 'Chiredzi',
    province: 'Masvingo',
    lat: -21.05,
    lng: 31.6667,
    popularSuburbs: ['Chiredzi Town', 'Tshovani'],
  },
  {
    id: 'karoi',
    name: 'Karoi',
    province: 'Mashonaland West',
    lat: -16.8167,
    lng: 29.6833,
    popularSuburbs: ['Karoi Town', 'Chikangwe'],
  },
  {
    id: 'gokwe',
    name: 'Gokwe',
    province: 'Midlands',
    lat: -18.2167,
    lng: 28.9333,
    popularSuburbs: ['Gokwe Centre', 'Sasame'],
  },
  {
    id: 'plumtree',
    name: 'Plumtree',
    province: 'Matabeleland South',
    lat: -20.4833,
    lng: 27.8167,
    popularSuburbs: ['Plumtree Town', 'Dingumuzi', 'Mathendele'],
  },
];

// Flat list for filter dropdowns (including All Areas & Other Custom)
export const ALL_ZIM_LOCATIONS_FILTER = [
  'All Areas',
  // Harare areas
  'Harare CBD',
  'Avondale',
  'Borrowdale',
  'Mbare Musika',
  'Eastlea',
  'Mount Pleasant',
  'Southerton',
  'Highfield',
  'Westgate',
  'Greendale',
  'Waterfalls',
  // Bulawayo areas
  'Bulawayo CBD',
  'Hillside',
  'Kumalo',
  'Nkulumane',
  'Luveve',
  'Cowdray Park',
  // Chitungwiza areas
  'Chitungwiza Makoni',
  'Chitungwiza Unit L',
  "Chitungwiza St Mary's",
  'Chitungwiza Zengeza',
  // Major towns
  'Mutare',
  'Gweru',
  'Kwekwe',
  'Masvingo',
  'Victoria Falls',
  'Kadoma',
  'Chinhoyi',
  'Marondera',
  'Norton',
  'Zvishavane',
  'Bindura',
  'Hwange',
  'Beitbridge',
  'Rusape',
  'Kariba',
  'Gwanda',
  'Chegutu',
  'Shurugwi',
  'Chipinge',
  'Ruwa',
  'Epworth',
  'Chiredzi',
  'Karoi',
  'Gokwe',
  'Plumtree',
  'Other (Custom Location)',
];

/**
 * Finds matching city by query
 */
export function findZimCity(query: string): ZimCity | undefined {
  const q = query.trim().toLowerCase();
  return ZIM_MAJOR_CITIES.find(
    (c) =>
      c.name.toLowerCase().includes(q) ||
      c.popularSuburbs?.some((s) => s.toLowerCase().includes(q))
  );
}
